version: "3.9"
services:
  mongo:
    container_name: mongo
    image: mongo:4.0
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./server
      network: host
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    env_file: 
      - .env
    links:
      - mongo
    depends_on: 
      - mongo

  frontend:
    build:
      context: ./client
      network: host
    volumes:
      - ./client:/app
    ports: 
      - "8080:8080"
    depends_on: 
      - backend
      - mongo

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:89.0
    ports:
      - "4444:4444"
      - "7900:7900"
    volumes:
      - /dev/shm:/dev/shm
  ai:
    build:
      context: ./AIService
      network: host
    ports: 
      - "5000:5000"
    volumes:
      - ./AIService:/usr/src/app
    depends_on: 
      - backend
    links:
      - frontend
      - backend